[workspace]
authors = ["Matthew Franz Kalch <kalch@outlook.com>"]
channels = ["conda-forge"]
name = "nbdev_cards"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
jupyterlab = ">=4.5.1,<5"
nbdev = ">=2.4.6,<3"
